// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function(grunt) {
    var _this = this;

    this.initConfig({
      pkg: this.file.readJSON('package.json'),
      watch: {
        files: ['**/**.coffee', '**/*.scss'],
        tasks: ['default']
      },
      coffee: {
        compile: {
          options: {
            bare: true,
            sourceMap: true
          },
          files: {
            'js/display.min.js': 'js/src/display.coffee',
            'js/admin.min.js': 'js/src/admin.coffee'
          }
        }
      }
    });
    this.loadNpmTasks('grunt-contrib-coffee');
    this.loadNpmTasks('grunt-contrib-watch');
    this.registerTask('default', ['coffee']);
    return this.event.on('watch', function(action, filepath) {
      return _this.log.writeln('#{filepath} has #{action}');
    });
  };

}).call(this);
